### ISSUE TITLE
Le joueur sort de la grile!!!

### ISSUE THREAD

**Issue by Krilivye** [BTS-SIO2-2013/ZombieKiller#1]
Je peux sortir de la grille!

**Comment by SpectroDT** [comment]
Bug: Le jouer peut sortir de la grille car elle n'a pas de limite.

Analyse: Ne pas permettre la sortie de la grille. Pas de message le signalant.

Il faut donc pour cela vérifier que le déplacement ne fasse pas sortir le personnage de la grille. 
S'il sort:  le déplacement est annulé.
S'il ne sort pas, le déplacement est effectué.

**Comment by Krilivye** [comment]
Je préfère avoir un message en tant qu'utilisateur : Déplacement Impossible!

**Comment by SpectroDT** [comment]
Demande: Afficher un message d'erreur lorsque le joueur essaye de sortir de la grille. 

Analyse en fonction de la demande de l'utilisateur: Si le déplacement fait sortir de la grille, annulé le déplacement et afficher le message d'erreur demandé. 

Concept: Faire une fonction booléenne qui vérifie si le déplacement peut être effectué (renvoi True), sinon renvoi False.
Dans la procédure de déplacement, on rajoute la fonction avant les différents déplacements. Si on ne peut pas se déplacer, on affiche le message d'erreur.

**Comment by morales12** [comment]
Résolu: Le joueur ne sort plus de la grille et un message s'affiche quand il se cogne dans un mur.

La méthode est fonctionnel mais peut être pas très "propre" il y a surement possibilité d'améliorer la fonction traitementCommande () de la classe Jeux.JAVA.
