### ISSUE TITLE
Bim le mur!

### ISSUE THREAD

**Issue by Krilivye** [BTS-SIO2-2013/ZombieKiller#2]
Je traverse les murs!

**Comment by mellonwid** [comment]
Il n'y a pas de test sur le type de case sur lequel le joueur va arriver. Il faut donc vérifier avant le déplacement sur quelle case le joueur va arriver et s'il peut s'y rendre. Les cases de type décors doivent être impossible à atteindre.

**Comment by bducastel** [comment]
Amélioration Logiciel : 

Analyse : Lorsque l'on joue on peut passer à travers les décors (murs, vitres....) cela ne devrait pas être possible il faut que les décors soient "solide".

Solution : 
Il faut donc créer une fonction dans la classe "Grille" testant la validité de la case et qui appelle une fonction testant si la case est de type décor.
On ajoute ensuite ce test  dans la classe "Jeux" dans la fonction déplacer.

**Comment by Tarzob** [comment]
Estimation du temps : 1heure 
création de la fonction test en cours...

**Comment by Tarzob** [comment]
Fonction test en attente de test^^ et fonction isValide et isDecors en cour dans la classe Grille

votre serviteur et son assistant 
Tarzob et Tallan3310

**Comment by Tarzob** [comment]
Push des fonctions isValide et isDecors et de leur test
